name: "Exporting and tests for pull request"
on: [pull_request]

jobs:
  pass_tests:
    name: Checking PR GUT tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: croconut/godot-tester@master
        with:
          version: "4.1"
          path: "godot"
          minimum-pass: "1.0"
          test-dir: "res://test"
          result-output-file: "test_results.xml"
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: gut_test_results
          path: ./godot/test_results.xml

  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: pass_tests
    if: ${{ success() }}
    name: Checking PR export
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.0.2

    - name: Install Godot third party libraries
      run: cd ./scripts && chmod -x ./setup.sh && ./setup.sh

    - name: Exporting game
      id: export
      uses: firebelley/godot-export@master
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1/Godot_v4.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1/Godot_v4.1-stable_export_templates.tpz
        relative_project_path: ./godot
        archive_output: true

  tests_failed:
    name: GUT tests have failed
    runs-on: ubuntu-latest
    needs: pass_tests
    if: ${{ failure() }}
    env:
      DAVID_USER: "${{ secrets.DAVID_USER }}"
      MIGUELP_USER: "${{ secrets.MIGUELP_USER }}"
      ANTONIO_USER: "${{ secrets.ANTONIO_USER }}"
      RODRO_USER: "${{ secrets.RODRO_USER }}"
      creator: '${{ github.event.pull_request.user.login }}'
    steps:
        - uses: actions/checkout@v3.0.2

        - name: Run script file
          run: |
            #!/bin/bash
            
            declare -A creator_dictionary

            creator_dictionary['miguelpOcacho']=$MIGUELP_USER
            creator_dictionary['DavidOcacho']=$DAVID_USER
            creator_dictionary['AntonioJose-OcachoGames']=$ANTONIO_USER
            creator_dictionary['RodroOcacho']=$RODRO_USER
            
            echo "creator_discord_id=${creator_dictionary[$creator]}" >> $GITHUB_ENV
          shell: bash

        - uses: actions/download-artifact@v3
          id: download
          with:
            name: gut_test_results

        - uses: sarisia/actions-status-discord@v1.12.0
          with:
            status: Failure 
            title: ❌ GUT tests have failed on `Pull Request` ❌
            description: |
              Please, <@${{ env.creator_discord_id }}>, run the tests locally and fix the issues before merging.
              Click on the `Workflow` field of this message and download the `gut_test_results` artifact in order to download the logs.
            username: GitHub CI-CL
            webhook: "${{ secrets.WEBHOOK_CI_CL }}"
            avatar_url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Pepe_Viyuela.jpg"
            content: "<@${{ env.creator_discord_id }}>"