name: "Passing GUT Tests"
on:
  workflow_call:

jobs:
  pass_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: croconut/godot-tester@master
        with:
          version: "4.1"
          path: "godot"
          minimum-pass: "1.0"
          test-dir: "res://test"
          result-output-file: "test_results.xml"
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: gut_test_results
          path: ./godot/test_results.xml