name: "Exporting the game (Github Releases -> (Windows))"
on:
  workflow_call:

jobs:
  pass_tests:
    uses: ./.github/workflows/reusable_pass_tests.yml

  export_game:
    name: Export Game (Windows)
    runs-on: ubuntu-latest
    needs: pass_tests
    if: ${{ success() }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      bump_version: patch
    steps:
    - name: Install Godot third party libraries
      run: chmod +x ./scripts/linux/setup.sh && ./scripts/linux/setup.sh

    - name: Installing wine for icon
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

    - name: Exporting game
      id: export
      uses: firebelley/godot-export@master
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
        relative_project_path: ./godot
        archive_output: true
        cache: true
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}