name: Updating Game dev branch with Home-Godot template

on:
  schedule:
    # Remember this is UTC -> UTC = CEST -2 -> UTC 5:30 | CEST 7:30
    - cron:  '30 5,17 * * *'

jobs:
  update_dev:
    runs-on: ubuntu-latest
    permissions: write-all
    if: ${{ github.repository != 'Ocacho-Games/Home-Godot' }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
      - run: |        
          #!/bin/bash
            
          chmod +x ./scripts/linux/get_latest.sh && ./scripts/linux/get_latest.sh
            
        shell: bash
